### ISSUE TITLE
Running VOLDOR in Colab

### ISSUE THREAD

**Issue by andrew-healey** [htkseason/VOLDOR#10]
I'm trying to use VOLDOR (not full, just VO) on Colab.

But I'm having problems with GPU kernel issues (`GPUassert : no kernel image is available for execution on the device`, `GPUassert : invalid device symbol`).

People have had this problem [before](https://github-com.translate.goog/htkseason/VOLDOR/issues/8?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=nui) and the prescribed solution was:
> Your card is good. Try to `setup.py` where `nvcc_machine_code` deleted, or based on [link](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/) change it.

So I looked up the typical Colab GPU, the Tesla K80, and found that it's using `code=sm_37` and `arch=compute_37`, so I input those into the the `setup.py` variation for my use-case, [`setup_linux_vo.py`](https://github.com/htkseason/VOLDOR/blob/master/slam_py/install/setup_linux_vo.py#L11).

But I still got the same error as before.
I'm super inexperienced with low-level CUDA compilation/build targets/how it interacts with GPU hardware/firmware, so I don't know why this approach isn't working. Could somebody please help me fix it?

[Here's](https://colab.research.google.com/drive/17o7NR25EZQUx4oyHGaWfF44pyUpF-XBK?usp=sharing) the code I'm running on Colab. If you run all cells, it will show you the `GPUassert` problems in the output of the last cell.

**Comment by htkseason** [comment]
Hi there,

At the latest update, I have removed `nvcc_machine_code`, this should give the maximum compatibility. So you may remove code=.../arch=... and try again. K80 is a little bit old, but most likely not his problem. Could you please share your cuda and gcc (or vs studio) version?

I never used colab before.. not sure if it will work.. Most likely the viewer based on opengl will not work.. Better try on a local machine.

**Comment by andrew-healey** [comment]
Thanks for your quick response. Here is the output of `nvidia-smi`, `nvcc --version`, and `gcc --version`:
```
Sun Oct 10 14:49:08 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.74       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8    29W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

On the topic of the viewer, I've disabled it in `demo.py` and I'm just trying to save poses for now. I'm planning to try to modify the code to save the point cloud to a file without using the viewer, but I'll only do that step if I can get the `GPUassert` problem solved.

In the case that `nvcc_machine_code` is removed in the default `build_linux_vo.py`, that makes me more confused about what's causing this problem, since it failed the `GPUassert`s even when I was using `build_linux_vo.py` without my custom `nvcc_machine_code`.

My code is shown if you click the link to [the Colab notebook](https://colab.research.google.com/drive/17o7NR25EZQUx4oyHGaWfF44pyUpF-XBK?usp=sharing), but I'll also put it here:

```
# Build VOLDOR
!git clone https://github.com/htkseason/VOLDOR
%cd VOLDOR/slam_py/install
!pip install -r requirements.txt
!python setup_linux_vo.py build_ext -i
%cd /content/VOLDOR
!cp ./slam_py/install/*.so demo

# Download flow and image files (TartanAir_OldTown)
!pip install -q gdown # Lets you download Google Drive files by ID
!gdown --id 1yhHLNOUIQ_2JNZ2EZEn5S6ra86peWZ-Y # tartan.zip
!unzip -oq tartan.zip

# Run VOLDOR
%cd demo
# I have edited demo.py and commented out every line importing or running the viewer, and disabling loop closure, so it just saves poses from VO
!python my_demo.py --fx 320 --fy 320 --cx 320 --cy 240 --bf 80 --flow_dir '../tartan/flow_mfn' --img_dir '../tartan/img' --disp_dir '../tartan/disp_mfn' --mode stereo --enable_loop_closure './ORBvoc.bin' --resize 0.5 --abs_resize 0.5 --save_poses poses
```

In case it makes the CUDA error any clearer, it's failing `GPUassert`s [here](https://github.com/htkseason/VOLDOR/blob/master/gpu-kernels/collect_p3p_instances.cu#L186), [here](https://github.com/htkseason/VOLDOR/blob/master/gpu-kernels/solve_batch_lambdatwist.cu#L69), and [here](https://github.com/htkseason/VOLDOR/blob/master/gpu-kernels/meanshift.cu#L58), where `gpuErrChk` is called right after moving memory to a given symbol.

**Comment by htkseason** [comment]
Thank you for sharing the code. I can reproduce the error in your colab environment. It is likely a compling problem.. I also got this when I upgrade my GPU from 10series to 30series but left sm_61/compute_61 in the code. Removing those fixed my case. But I was not able to fix yours... Wonder if a GPU with higher compute compatibilty will work? 

I will let you know if I have updates on this.. Please also let me know if you fixed it.

**Comment by andrew-healey** [comment]
It looks like Colab's software (something in their environment, I'm not sure what) is buggy, not the Tesla K80 itself; I just got VOLDOR to run on Vast.ai on a K80. [Here's](https://gist.github.com/Sesamestrong/29d8f85c9d2d69891ef709ea5ae9e640) the output, if you're interested.
The software versions on this were:
```
Sun Oct 10 22:17:37 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:68:00.0 Off |                    0 |
| N/A   54C    P0    74W / 149W |      0MiB / 11441MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by htkseason** [comment]
Great, happy to hear you got it worked! Feel free to let me know if you have further questions.
