### ISSUE TITLE
How to extract the point cloud?

### ISSUE THREAD

**Issue by yjjuan** [htkseason/VOLDOR#12]
Hi htkseason,
thanks for sharing your wonderful work. **I have successfully run the full-SLAM mode on KITTI dataset. However, I still don't know how to extract point cloud as mentioned in your paper.** Could you guide me what's the next step to extract point cloud? I have attach the screenshot when I finish slam task.

Looking forward to your reply:)

![Screenshot from 2022-01-10 14-45-01](https://user-images.githubusercontent.com/36185362/148727758-2f8ce4a5-3839-483d-9033-2faa29f0a869.png)

**Comment by htkseason** [comment]
Hi yjjuan,

Happy to hear you got the system running. 
To extract the point cloud, press 'm' key in the viewer. It will create a ply file for you (find it somewhere in your current folder). You may adjust the density/range in the viewer in advance. (See `Tips` section in git README.)

I noticed your viewer seems not running correctly.. Perhaps we should fix from there.

Best,
Min

**Comment by yjjuan** [comment]
Hi Min, thanks for your suggestion. It seems that viewer didn't work correctly within my docker. I am still working on that. But is it possible to print out x,y,z position of pointcloud first without viewer??

Best,
Kevin

**Comment by htkseason** [comment]
Hi Kevin,

Sorry it is not possible for now.. I guess a simple alternative is to project the saved depth maps to point clouds while thresholding them with depth confidence and maximum depth.

Best,
Min

**Comment by yjjuan** [comment]
I downgraded my CUDA from 11.2 to 10.2 and installed corresponding libnvidia-gl via `apt install -y libnvidia-gl-440`. Problem get solved! CUDA and GPU information is shown as below. Thanks.
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.95.01    Driver Version: 440.95.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 930MX       Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0    N/A /  N/A |     96MiB /  2004MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
             
```

**Comment by yjjuan** [comment]
Hi Min,
Sorry for coming up with another problem. I have successfully built the point cloud from KITTI-03 dataset you provided. **However, the point cloud are all composed of black dots, rather than colorful ones as shown in your paper. Could you teach me how to draw color to the pointcloud??** Thanks again.

Here is my screenshot.
![dense_reconstruction_kitti_03](https://user-images.githubusercontent.com/36185362/149460592-b8304e18-687f-4ed9-a608-a17fa76ed087.png)

Best,
kevin
