### ISSUE TITLE
Camera pose is always truncated.

### ISSUE THREAD

**Issue by xji-apex** [htkseason/VOLDOR#13]
Hello !!! Thank you for your sharing work !!! It's an amazing job!

I test the VO pipeline with my own optical flow data(w:346 h:260 pixels). The direction of trajectory is basically true with the provided config parameters. The accuracy and fluency are so bad.

I look up the log， the pose_rigidness_density is often lower than the parameters of trunc_rigidness_density（0.05f）which leads to the Optimization failure for camera pose and truncation?  The performance is so bad that I may not lower the trunc_rigidness_density value.

The log is as followed:
![sendpix0](https://user-images.githubusercontent.com/71243343/155486136-cafb7761-e801-4a54-8aa1-f4dae3efd023.jpg)
![image](https://user-images.githubusercontent.com/71243343/155486304-30b00526-4960-46e4-8604-b3c85932a74e.png)
![image](https://user-images.githubusercontent.com/71243343/155486466-2fbae8cd-40cf-4433-8c8b-c05331e4758e.png)

This is really due to the difference in the optical flow data.  
So could you give me some advice about how to apply it with better accuracy？
Thanks a ton ！！！

**Comment by htkseason** [comment]
Hello, 

Thanks for your interest in our work.

Seems like your confidence map is very sparse and few pixels are being tracked. In such case, it is hard to chain multiple frames and the truncation is an expected behavior.

Could you check if the camera parameters are correct. If you scale down the input optical flow size, make sure scale down the optical flow magnitudes and the camera intrinsic as well.

Also, could you the OF method are you using? Does a different optical flow (e.g. MaskFlowNet) works for you?

**Comment by xji-apex** [comment]
Yes, as you say， Its confidence map is so sparse, because the optical flow is semi-dense. The VOLDOR performs well with the dense OF data(e.g. KITTI-03) . I want to try if the VOLDOR could be also well with the semi-dense OF？

So I make some adjustments to test：
First, modify the parameters of the camera（fx，fy， cx，cy）which is the same as the camera model of OF methods。

Then, because of the semi-dense， I get rid of the points without OF value and use the points with OF value to update the pose, rigidnesses map, and depth map. The specific modified function is：
- bootstrap（）:  solve the Essential Mat only using the pixels with OF value and define the depth of none-OF-value pixels as min_depth (1e-2f);   
- optimize_cameras():  collect pnp points is also with the OF value.
- optimize_depth(): the compute_pixel_cost() and update_rigidnesses()  also ignore the  none-OF-value pixels .

I'm not sure if the new edition for VOLDOR  with semi-dense OF  is feasible？？？  
Hopefully, you could give some advice to adjust!!!

Thank you for your kind attention and Looking forward to your reply ! !!

**Comment by htkseason** [comment]
It is an very interesting branch to explore. IMO, your fixes make sense but not enough. VOLDOR utilizes the dense property and poses spatial smothness on the depth/rigidness maps. Inputing sparse OF is not preferred by the current optimizer. Moreover, VOLDOR relies more on the flat regions than the corners/edges. I see your sparse OF clusters around the edges, which is also not preferred by the current framework (difficult to chain multiple frames). Perhaps an in-depth new optimizer that can utilize the sparse property is required for your task. But definitely I see bright future from your topic. Good luck.
