### ISSUE TITLE
光流方法选取和pyvoldor_full.xxx.so编译（ recompile with -fPIC）

### ISSUE THREAD

**Issue by xji-apex** [htkseason/VOLDOR#15]
你好，一直在关注VOLDOL的工作，感谢你的分享！！！

有两个问题想要咨询一下：
1. 输入的光流是否需要进行固定形式的处理？（测试的VOLDOR 对光流的敏感度感觉有点高？？）
          我是在demo data 上进行测试，利用其中的img图片，选取[PWC-Net]框架进行光流预测，将光流结果.flo输入进VOLDOR，由于PWC-Net输出的光流是原图片尺寸（1242 X 375）,而demo data里的光流flo是（621 X 188）,因此，为统一，在VOLDOR的resize上进行了相应调整，结果如下：
PWC-Net的结果（resize = 0.25）
![sendpix2](https://user-images.githubusercontent.com/71243343/157166144-ea594ea2-b523-4be8-8bf0-086525ab1f4d.jpg)
原demo data的flo输入：（resize = 0.5）
![sendpix3](https://user-images.githubusercontent.com/71243343/157166181-b643a07a-f864-47c2-bd0d-b04926105755.jpg)

从产生的轨迹上看，结果上存在较大差异。。。所以，想问下造成的可能原因以及VOLDOR 管道对光流结果的鲁棒性如何？

2. 小分辨率的数据集测试（346 X 260），tracking lost问题。
          选取了一份[公开的数据集]，其像素光流结果gt是由位姿poses 和深度图depth解算而来。将光流真值gt以及对应的相机内参（fx，fy，cx，cy）输入到voldor中：
![sendpix4](https://user-images.githubusercontent.com/71243343/157168760-695bcf80-f3de-4d61-b332-3aa05309fb65.jpg)

直线上轨迹稍有波动，但是精度尤其是在转弯时容易产生 tracking lost 问题。可视化了一下光流真值（如上图可见），其光流效果与[MaskFlowNet] or [PWC-Net]的输出效果有较大不同，是否是这个输入形式的影响，或者有哪些需要改进调整的方面？

BTW， pyvoldor_full.xxx.so编译报错（ recompile with -fPIC），和issue#8一样，系统配置为ubuntu18.04和gcc/++-7，我尝试在Extension（）函数内添加-fPIC参数，但是没有成功：
`gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xji/anaconda3/envs/VOLDOR/lib/python3.6/site-packages/numpy/core/include -I/usr/include/eigen3 -I/home/xji/anaconda3/envs/VOLDOR/include/python3.6m -c ../../pose-graph/pgo.cpp -o build/temp.linux-x86_64-3.6/../../pose-graph/pgo.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xji/anaconda3/envs/VOLDOR/lib/python3.6/site-packages/numpy/core/include -I/usr/include/eigen3 -I/home/xji/anaconda3/envs/VOLDOR/include/python3.6m -c ../../pose-graph/py_export.cpp -o build/temp.linux-x86_64-3.6/../../pose-graph/py_export.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -L/home/xji/anaconda3/envs/VOLDOR/lib -Wl,-rpath=/home/xji/anaconda3/envs/VOLDOR/lib,--no-as-needed build/temp.linux-x86_64-3.6/pyvoldor_full.o build/temp.linux-x86_64-3.6/../../voldor/utils.o build/temp.linux-x86_64-3.6/../../voldor/geometry.o build/temp.linux-x86_64-3.6/../../voldor/voldor.o build/temp.linux-x86_64-3.6/../../voldor/py_export.o build/temp.linux-x86_64-3.6/../../frame-alignment/align_frame.o build/temp.linux-x86_64-3.6/../../frame-alignment/py_export.o build/temp.linux-x86_64-3.6/../../pose-graph/pgo.o build/temp.linux-x86_64-3.6/../../pose-graph/py_export.o -L. -L/usr/local/lib -L/usr/local/cuda/lib64 -L/home/xji/anaconda3/envs/VOLDOR/lib -lgpu-kernels -lcudart -lceres -lglog -lamd -lbtf -lcamd -lccolamd -lcholmod -lcolamd -lcxsparse -lgraphblas -lklu -lldl -lrbio -lspqr -lumfpack -llapack -lblas -lgcc -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_viz -lopencv_core -lpython3.6m -o /home/xji/project/VOLDOR/slam_py/install/pyvoldor_full.cpython-36m-x86_64-linux-gnu.so
/usr/bin/ld: ./libgpu-kernels.so(tmpxft_00004ed1_00000000-40_align_frame.o): relocation R_X86_64_PC32 against symbol `_Z31apply_weighted_sqrt_cauchy_lossibb' can not be used when making a shared object; **recompile with -fPIC**
/usr/bin/ld: 最后的链结失败: 错误的值
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
`

**Thank you for your sharing again and Looking forward to your reply !!!**

**Comment by htkseason** [comment]
Thanks for your interest in our work.

PWC-Net和MaskFlowNet我这边试下来的结果是看不出差异的。你确认下camera intrinsic输入的对不对，因为demo里的`--resize`是会同时scale intrinsic的，需要确保输入的光流和intrinsic对应。比如KITTI-03，如果你OF输入是`1242 X 375`，那intrinsic就应该是`--fx 720 --fy 720 --cx 608 --cy 172 --bf 384`，然后再`--resize 0.25`。（另外如果改变了输入的OF尺寸，记得同时scale他的magnitude。）

同样对于你用的第二份数据集，先确认下 1）intrinsic是否与OF的尺寸匹配，2）如果改变过OF的尺寸，是否同时scale了magnitude。我没有测试过semi-dense的OF，你这个density还可以，我觉得问题不大。346 X 260的尺寸也是我测试时候经常用的，应该也问题不大。

编译的问题我需要再研究下。。

**Comment by xji-apex** [comment]
你好，那个-fPIC编译的问题解决了！

.cu文件编译时，我的默认项没有带-fPIC 选项，因此，在gpu_kernel_build_cmd中添加上--compiler-options "-shared -fPIC"参数即可，setup_linux_***.py的第16行：
`gpu_kernel_build_cmd = f'/usr/local/cuda/bin/nvcc --compiler-options "-shared -fPIC" {gpu_sources_cpp} {gpu_sources_cu} -lib -o libgpu-kernels.so -O3 {nvcc_machine_code}'`

对于KITTI-03数据集，修改OF尺寸后，PWC-Net确实得到了和demo data相似的结果，感谢你的建议！

对于第二份数据集（346 X 260），他是一个单目mono模型，OF尺寸和相机内参也是一致的（resize =  abs_resize =0.5），因为想测一下VOLDOR在仅光流输入下的效果，但是其得到的轨迹形状和位姿gt差距甚远，可能是density或者其他参数的问题？目前还在找原因，如果您有相关建议，还望不吝赐教，十分感谢！
![image](https://user-images.githubusercontent.com/71243343/158023084-76671109-57a5-46dd-b69c-bd931983dd87.png)

**Comment by htkseason** [comment]
我测试后会将fPIC和shared加入编译，感谢分享！

关于你第二个数据集的问题：
1）semi-dense的光流我想了下确实可能不兼容，一方面会造成depth的propagation不收敛，另一方面会造成OF之间的光流chain不起来，会lost tracking，这些都是设计的问题，没考虑过非dense的情况。也许可以试一下naive的densification，比如[bilateral solver](https://arxiv.org/abs/1511.03296)，然后输入dense的OF试一下。
2）也可以试着调一下basefocal看看会不会好，变好的希望不大。
3）现在的system没有特别的initialization scheme，monocular下会用最初的2帧init，需要确保一开始的2帧之间有足够的baseline。
4）你po的结果看着很像相机参数和OF不match的样子，也许可以再debug一下，输入的OF的size、magnitude和camera intrinsic得match，这三个是会一起被resize的。还有就是因为OF是从depth和pose算出的，所以也可以check一下有没有big value/inf/nan，比如你第三张图OF的最右的亮块有点可疑。
