### ISSUE TITLE
Abort ImportError when import pyvoldor_full 

### ISSUE THREAD

**Issue by liangjunAI** [htkseason/VOLDOR#16]
您好，我执行完setup_linux_full.py生成对应的.so库，但在测试demo时，import pyvoldor_full会报错，错误如下：
pyvoldor_full.cpython-39-x86_64-linux-gnu.so: undefined symbol: cusolverDnSetStream

**Comment by htkseason** [comment]
你好，只编译vo的话有这个问题吗？

**Comment by liangjunAI** [comment]
感谢回复，编译vo后import pyvoldor_vo不会报错，full的会报错。
还有个问题需要请教，python demo.py 
--fx 320 --fy 320 --cx 320 --cy 240 --bf 80参数中的--bf是如何设置呢

**Comment by htkseason** [comment]
import出错还挺奇怪的，cuda部分vo和full用的是一样的，而且我没用到cusolver。。感觉可能是ceres没装好？

bf指的是baseline*focal，会影响scale。如果input了从stereo matching得来的dispairty，就需要指定这个参数。如果是monocular/rgbd的input，可以当作超参调一调，默认应该是0.5*focal。
