### ISSUE TITLE
cannot Build Full SLAM Pipeline

### ISSUE THREAD

**Issue by guijuzhejiang** [htkseason/VOLDOR#17]
I follow the instruction to build on ubuntu18,but i got error below when i tried to run 'python3 setup_linux_full.py build_ext':

/usr/bin/ld: cannot find -lamd
/usr/bin/ld: cannot find -lbtf
/usr/bin/ld: cannot find -lcamd
/usr/bin/ld: cannot find -lccolamd
/usr/bin/ld: cannot find -lcholmod
/usr/bin/ld: cannot find -lcolamd
/usr/bin/ld: cannot find -lcxsparse
/usr/bin/ld: cannot find -lgraphblas
/usr/bin/ld: cannot find -lklu
/usr/bin/ld: cannot find -lldl
/usr/bin/ld: cannot find -lrbio
/usr/bin/ld: cannot find -lspqr
/usr/bin/ld: cannot find -lumfpack
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-g++' failed with exit status 1

please help.

**Comment by htkseason** [comment]
Can you build VO-only?

**Comment by guijuzhejiang** [comment]
yes i can

> Can you build VO-only?

**Comment by htkseason** [comment]
The listed libraries are Ceres dependencies. If you installed ceres+suitesparse correctly, they should be found... Have you ran `sudo make install` to register the ceres?

**Comment by guijuzhejiang** [comment]
thank u,I haven't installed the libsuitesparse before, but now i get 'undefined symbol: cusolverDnSetStream' when i run demo.py

> The listed libraries are Ceres dependencies. If you installed ceres+suitesparse correctly, they should be found... Have you ran `sudo make install` to register the ceres?

**Comment by guijuzhejiang** [comment]
![Screenshot from 2022-05-10 13-53-38](https://user-images.githubusercontent.com/57936895/167557842-26a91c3c-33ea-4493-9013-bee57f22f016.png)
i add '-l cusolver', '-l cublas' ,  and i got 'Full pyvoldor module loaded.'  but the tmpkf_depth_conf and tmpkf_depth windows are not working

**Comment by htkseason** [comment]
That's weired, those are just opencv imshow. Does the 3D viewer reponse? Can you control the 3D viewer with your mouse?

**Comment by guijuzhejiang** [comment]
3D viewer work fine, i can control my mouse

> That's weired, those are just opencv imshow. Does the 3D viewer reponse? Can you control the 3D viewer with your mouse?

**Comment by donkeymouse** [comment]
> ![Screenshot from 2022-05-10 13-53-38](https://user-images.githubusercontent.com/57936895/167557842-26a91c3c-33ea-4493-9013-bee57f22f016.png) i add '-l cusolver', '-l cublas' , and i got 'Full pyvoldor module loaded.' but the tmpkf_depth_conf and tmpkf_depth windows are not working

Hey. Can you tell me more in depth about how you added '-l cusolver', '-l cublas'?? I am quite new to this so I'm not so sure about hwere to add the following lines you have provided
