### ISSUE TITLE
demo data

### ISSUE THREAD

**Issue by frischzenger** [htkseason/VOLDOR#18]
the folder disp_mfn in TartanAir-oldtown, demo_data , which is *.flo files, but not depth files.

**Comment by htkseason** [comment]
Thanks for trying out our code. The `.flo` files in disp folder are optical flows computed from left to right (rectified stereo). We use its x-component as the disparities. The depth are then computed using `basefocal` divided by `disp`.
Simply specify that folder as disp input, and it will work :)
