### ISSUE TITLE
CPU support?

### ISSUE THREAD

**Issue by varungiridhar** [htkseason/VOLDOR#19]
Hi, 

This project requires CUDA support, but I wanted to know if there was a way to implement VOLDOR as a CPU-based version that runs lighter 😭😭. Please let me know what would be the appropriate way to implement this; which part of the code to get started, ex: optical flow, depth estimation, local mapping. Thanks!

**Comment by htkseason** [comment]
Sorry, there's no way to skip CUDA :(
The dense pixels are very computationally heavy, your cpu won't be happy about the task.
