### ISSUE TITLE
Nvidia optical flow SDK?

### ISSUE THREAD

**Issue by sequoia-hope** [htkseason/VOLDOR#2]
Hello!

Wow you’ve released this with perfect timing for me! I’m going to have to give this a spin but I had a question:

Are you familiar with the NVIDIA optical flow SDK? On their new GPUs it can produce dense optical flow at very high frame rates. I may test this in the future but since I didn’t see it in the readme I wanted to ask about it. I believe it produces .flo so I expect it would work, so this is kind of a PSA about the high frame rate it can offer.

https://developer.nvidia.com/opticalflow-sdk

cheers!

**Comment by htkseason** [comment]
Hi there,

Thank you for asking the question. This SDK is SUPER COOL. I was not aware of it before, thus cannot provide futher information. I definitely will try it in the future. I will leave the issue open for sharing updates.

Thanks,
Min
