### ISSUE TITLE
Regarding Input Video 

### ISSUE THREAD

**Issue by pradyumnakulkarni87** [htkseason/VOLDOR#21]
Thanks for this great work .
Stuck at a point  , How can I use a video generated by my mobile camera, what should be the processes required to make it use full and How I can provide it to SLAM system. 
Thanks in advance

**Comment by htkseason** [comment]
Maybe first dump the video into image sequences and run optical flow method on it.
You will need to know the camera intrinsic as well.
More info is in the README, Prepare Data section. You need have something like the demo data I shared.

**Comment by pradyumnakulkarni87** [comment]
> Maybe first dump the video into image sequences and run optical flow method on it. You will need to know the camera intrinsic as well. More info is in the README, Prepare Data section. You need have something like the demo data I shared.

A big Thank you for replying, 
stuck at how can I apply my video to optical flow method(plz specify the method) and how can i create the folder like disp_mfn and flow_mfn ....
it will be great if you help me out , 
Thanks in advance

**Comment by htkseason** [comment]
flow_mfn/disp_mfn are both optical flow outputs from MaskFlowNet. You can try other OF methods you like, for example RAFT.
Optical flow (flow_mfn) runs from frame t to t+1.
Disparity runs from left frame to right frame of same time stamp.
