### ISSUE TITLE
Do i need to adjust the parameter alpha and beta of the PDF of the Fisk distribution in a new situation? 

### ISSUE THREAD

**Issue by betterCZ101** [htkseason/VOLDOR#27]
I have a question that when i use the VOLDOR in a new situation ranther than the KITTI Dataset, do i i need to adjust the parameter alpha and beta of the PDF of the Fisk distribution? Since i notice that the alpha and belta are estimated from KITTI empirical data using, whether it has generality?

**Comment by htkseason** [comment]
Idealy, you can adjust. But empirically, I see minor performance gain by refitting the residual model to different datasets. I am using the given one for TartanAir dataset as well.

**Comment by betterCZ101** [comment]
thanks a lot！



At 2023-03-25 18:52:36, "Min" ***@***.***> wrote:

Idealy, you can adjust. But empirically, I see minor performance gain by refitting the residual model to different datasets. I am using the given one for TartanAir dataset as well.
