### ISSUE TITLE
When use the VOLDOR on a new dataset，i have a question 

### ISSUE THREAD

**Issue by betterCZ101** [htkseason/VOLDOR#28]
when use the VOLDOR on a drone dataset，i could work， but when mapping， there are some frames track lost，and the mapping
result is below.
Could you please help me analyse the question or just give some advice to solve the question?

<img width="215" alt="79d31ec4-b3f7-47f6-b2c3-52c044c51598" src="https://user-images.githubusercontent.com/116178220/231204914-2ed6a177-d85c-4faa-8327-240872e945a6.png">

**Comment by htkseason** [comment]
I assume the dataset is monocular. Some ideas you may try:
1) Make sure the first two frames have sufficient baseline, since the world scale is initialized from there.
2) Check calibration. When resizing input size, optical flow vectors and intrinsics need to be scaled accordingly. Also try to adjust [basefocal], see README [How to pick basefocal].
3) When estimating optical flows, skip those frames with very small changes. 

If you see the depth map gradually truns from a reasonable one to all white/black, it is the scale drift. In this case, you may want to try COLMAP, which is very good at monocular, although not real-time.

**Comment by betterCZ101** [comment]
Hi, Thanks for your advice, we found that the PWCNet we used have some problem leading to the poor performance of the results.  So for the better and easier understanding of your excellent work, we just use the mono pattern using the demo data you provided. considering the advice you provided, we got the results below：
![1280X1280 (2)](https://user-images.githubusercontent.com/116178220/233787705-0b4f6c6f-6e48-4bb6-8b20-dc46a234fd0d.png)
![1280X1280 (2)](https://user-images.githubusercontent.com/116178220/233787710-f378eaea-2f3d-454d-8f9f-25c1bf4ba5db.png)






We elaborately to adjust the "basefocal", but the results is disappointing.
By the way, we meet the same question as the #23 "Error: Loop closure not available. Cannot load pyDBoW3 module."
Thus, if the disappointing result is caused by the lack of the loop closure or just there need some auxiliary information to improve the performance of the mono.

Any another  two questions:
1.we just change the parameter "basefocal" 182 to 181 the results have changed a lot.
![1280X1280 (1)](https://user-images.githubusercontent.com/116178220/233787717-69b4c70f-7476-4164-8252-45ac0f3098ef.png)

![7d9d556a-bdf0-431a-9144-580ada0796cc](https://user-images.githubusercontent.com/116178220/233787733-e219064f-7cf9-43c2-8cd5-9fe06fa72696.png)

2.according to the first advice, the "sufficient baseline" if is the  parameter "basefocal" or it is another?

**Comment by htkseason** [comment]
Thank you for reporting the results! 

The results you shown are reasonable w/o loop closure. The monocular setup has scale drift, which needs loop closure to enforce the global consistency. While changing the basefocal could also affect the drift pattern. 

In our CVPR submission, we enforce the scale consistency with ground plane estimation. (detailed in first section in appendix) I kept the function "estimate_kitti_ground_plane" in geometry.cpp, but not using it anymore. Running our system under stereo mode and providing disparity estimations can also eliminate the drift.

Please let me know if you have more questions.

**Comment by betterCZ101** [comment]
So,  with respect to the the iusse#23  "Cannot load pyDBoW3 module. this problem: I have put pyDBoW3 in my workspace, but pyDBoW3 cannot be loaded" is there any solution ?

**Comment by htkseason** [comment]
Maybe try 1) put it under different paths (e.g. current path / path of demo.py / path of voldor_slam.py) or 2) use "pip install" to install it into python libs.

**Comment by betterCZ101** [comment]
hi, it doesn't work, and i infer that it the libboost is not compatible. I install the ubuntu 18.04 from scratch. When i use the command"python setup_win_vo.py build_ext -i", it has the error"gcc: error:/wd4819: No such file or directory", if the gcc version is not suitable? i use the gcc5.5 and gcc7.0 ,both have the problem.

**Comment by betterCZ101** [comment]
the problem above i have finished. And i have make the whole process successfully. and i have other questions.
1.In the stereo pattern with loop closure,  the squence 03 is just a trajectory can't meet the condition of the loop closure, namely the car did not come back around the same place, why the result had improved compared to that without the loop closure?
![89664ac5-d156-4fb7-bd8c-a6dbd8051919](https://user-images.githubusercontent.com/116178220/236631118-474f4c36-8c11-4cfc-880b-03e05bfe690d.png)

![16b1e4ee-593a-4dc9-986e-b8c31a424d18](https://user-images.githubusercontent.com/116178220/236630644-04596af0-37c2-4096-9fcf-fb520e59afd8.png)

2.In the mono pattern with loop closure, why the result of squence 05 like above, is there any solution?

![5780847a-ff7e-40a0-a3d1-4670441fe64c](https://user-images.githubusercontent.com/116178220/236630669-cb006cbb-0772-4dbd-9ab8-22a67896c553.png)
