### ISSUE TITLE
windows  install problem

### ISSUE THREAD

**Issue by baonudesifeizhai** [htkseason/VOLDOR#3]
> 

-  
![image](https://user-images.githubusercontent.com/85092850/120140694-a5fb3800-c20d-11eb-853f-011d8a619a93.png)
这个 cl.exe 本地我有，而且也可以跑其他cpp 
但是为啥这里不行啊。。。

**Comment by baonudesifeizhai** [comment]
build vo only

**Comment by htkseason** [comment]
没遇到过，不太清楚。。nvcc既然编译出来了，那vs应该是装好了的。你手动call一个cl看看找得到不，找不到的话就是环境变量没设好，找到的话更新下cython看看。

**Comment by baonudesifeizhai** [comment]
老哥我换 ubuntu了   gpu-kernels.so找不到  
这个是cuda自带的还是windows一样得下好放demo里面？

**Comment by htkseason** [comment]
这个是编译出来的，如果跑完setup没出现的话，说明编译出问题了。

**Comment by baonudesifeizhai** [comment]
![image](https://user-images.githubusercontent.com/85092850/120765981-59d13000-c54c-11eb-8b87-4d93763daecd.png)
![image](https://user-images.githubusercontent.com/85092850/120766176-8d13bf00-c54c-11eb-9744-ce6a11a86237.png)
老哥你在hoboken吗  我可以去找你

**Comment by baonudesifeizhai** [comment]
nvcc fatal   : Don't know what to do with '{nvcc_machine_code}'
显卡版本gtx 1060  cuda 9.1 
老哥你在hoboken吗 我可以去找你

**Comment by htkseason** [comment]
你可以给我发邮件。
