### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by sequoia-hope** [htkseason/VOLDOR#4]
Hello! This looks like a good candidate for Docker.

Have you tried bringing it up in docker? I may try that soon but I thought I'd ask in case you have a dockerfile in progress.

**Comment by htkseason** [comment]
Hi,
Thank you for the suggestion. Unfortunately, I am not familiar with docker. If anyone voluntarily provided a docker support, I am happy to provide the link in README.

**Comment by sequoia-hope** [comment]
Great I will let you know if I make any progress with it.

**Comment by sequoia-hope** [comment]
I made a quick dockerfile as a starting point. It builds the VO only, as I wanted to get the basic structure working before including the Ceres build.
https://github.com/tlalexander/VOLDOR/blob/master/Dockerfile

To build Ceres I will be looking at this file:
https://github.com/mapillary/OpenSfM/blob/master/Dockerfile.ceres2

I've not tested running any code, I really just wanted to get the rough dockerfile going.

**Comment by htkseason** [comment]
Looks great! If you would like to share them, you can keep the docker files in a separate git repository, so I can link them in submodule and readme. Thanks.

**Comment by sequoia-hope** [comment]
Sure! Actually prob link to this issue in the readme so someone can also see the discussion. I'll keep the file in my fork for anyone to see.
