### ISSUE TITLE
Reproduce VO performance

### ISSUE THREAD

**Issue by jinyummiao** [htkseason/VOLDOR#9]
Hi, thanks for your work. 
I have successfully built VO pipeline according to your instructions. However, it fails to localize or map when I run VO pipeline in monocular mode. The output log may be helpful to fix this problem:

GPUassert : invalid device symbol
../../gpu-kernels/collect_p3p_instances.cu at line 186
GPUassert : no kernel image is available for execution on the device
../../gpu-kernels/reduce_vector_sum.h at line 53
Tracking lost at 6

Looking forward to your reply:)

**Comment by jinyummiao** [comment]
The command I used:
python demo.py --fx 360.76885 --fy 360.76885 --cx 304.77965 --cy 86.427 --bf 192.19074 --flow_dir '../KITTI-03/flow_mfn' --img_dir '../KITTI-03/img' --mode mono --resize 0.5 --abs_resize 0.25

**Comment by htkseason** [comment]
Hi there,
It seems a compling problem. Could you share with me your OS, GPU model and CUDA version?
What is the `nvcc_machine_code` you are using in your 'setup.py'?

**Comment by jinyummiao** [comment]
I compiled the project on a laptop with GTX 1660Ti GPU, CUDA 10.0, Ubuntu 18.04.
I have tried the original `nvcc_machine_code='-m64 -arch=compute_61 -code=sm_61'`, `ncc_machine_code=''` and `nvcc_machine_code='-m64 -arch=compute_75 -code=sm_75'` (referring to [this](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/)). All failed...

**Comment by jinyummiao** [comment]
It is concluded as a compling problem. I have fixed the problem. Thanks for your kindly help!
